### ISSUE TITLE
[Bug]: location_name not fillable

### ISSUE THREAD

**Issue by justin-actablue** [tastyigniter/ti-ext-api#57]
### What happened?

adding a location via API

json:
```json
{
    "location_name": "Test",
    "location_email": "info@example.com",
    "location_address_1": "Testing 123",
    "location_country_id": 150,
    "options":{
        "auto_lat_lng": true
    }
}
```

all with the latests versions (api(main/master) & tasty (develop))

### What did you expect to happen?

expected to add the location as documentation stated.

### Version

3.0.6

### Relevant log output

```shell
response:

{
    "message": "Add [location_name] to fillable property to allow mass assignment on [Admin\\Models\\Locations_model].",
    "status_code": 500,
    "debug": {
        "line": 425,
        "file": "/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",
        "class": "Illuminate\\Database\\Eloquent\\MassAssignmentException",
        "trace": [
            "#0 /var/www/html/extensions/igniter/api/classes/AbstractRepository.php(77): Illuminate\\Database\\Eloquent\\Model->fill(Array)",
            "#1 /var/www/html/extensions/igniter/api/actions/RestController.php(87): Igniter\\Api\\Classes\\AbstractRepository->create(Object(Admin\\Models\\Locations_model), Array)",
            "#2 [internal function]: Igniter\\Api\\Actions\\RestController->store()",
            "#3 /var/www/html/vendor/tastyigniter/flame/src/Traits/ExtendableTrait.php(451): call_user_func_array(Array, Array)",
            "#4 /var/www/html/vendor/tastyigniter/flame/src/Support/Extendable.php(42): Igniter\\Flame\\Support\\Extendable->extendableCall('store', Array)",
            "#5 [internal function]: Igniter\\Flame\\Support\\Extendable->__call('store', Array)",
            "#6 /var/www/html/extensions/igniter/api/classes/ApiController.php(43): call_user_func_array(Array, Array)",
            "#7 /var/www/html/extensions/igniter/api/vendor/illuminate/routing/ControllerDispatcher.php(45): Igniter\\Api\\Classes\\ApiController->callAction('store', Array)",
            "#8 /var/www/html/extensions/igniter/api/vendor/illuminate/routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Igniter\\Api\\ApiResources\\Locations), 'store')",
            "#9 /var/www/html/extensions/igniter/api/vendor/illuminate/routing/Route.php(204): Illuminate\\Routing\\Route->runController()",
            "#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()",
            "#11 /var/www/html/extensions/igniter/api/vendor/illuminate/pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#12 /var/www/html/extensions/igniter/api/vendor/dingo/api/src/Http/Middleware/Auth.php(55): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#13 /var/www/html/extensions/igniter/api/vendor/illuminate/pipeline/Pipeline.php(167): Dingo\\Api\\Http\\Middleware\\Auth->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#14 /var/www/html/extensions/igniter/api/vendor/illuminate/routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#15 /var/www/html/extensions/igniter/api/vendor/illuminate/pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#16 /var/www/html/extensions/igniter/api/vendor/illuminate/routing/Middleware/ThrottleRequests.php(127): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#17 /var/www/html/extensions/igniter/api/vendor/illuminate/routing/Middleware/ThrottleRequests.php(103): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest(Object(Dingo\\Api\\Http\\Request), Object(Closure), Array)",
            "#18 /var/www/html/extensions/igniter/api/vendor/illuminate/routing/Middleware/ThrottleRequests.php(55): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter(Object(Dingo\\Api\\Http\\Request), Object(Closure), 'api', Object(Closure))",
            "#19 /var/www/html/extensions/igniter/api/vendor/illuminate/pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure), 'api')",
            "#20 /var/www/html/extensions/igniter/api/vendor/dingo/api/src/Http/Middleware/PrepareController.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#21 /var/www/html/extensions/igniter/api/vendor/illuminate/pipeline/Pipeline.php(167): Dingo\\Api\\Http\\Middleware\\PrepareController->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#22 /var/www/html/extensions/igniter/api/vendor/illuminate/pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Dingo\\Api\\Http\\Request))",
            "#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Dingo\\Api\\Http\\Request), Object(Illuminate\\Routing\\Route))",
            "#26 /var/www/html/vendor/tastyigniter/flame/src/Router/CoreRouter.php(22): Illuminate\\Routing\\Router->dispatchToRoute(Object(Dingo\\Api\\Http\\Request))",
            "#27 /var/www/html/extensions/igniter/api/vendor/dingo/api/src/Routing/Adapter/Laravel.php(88): Igniter\\Flame\\Router\\CoreRouter->dispatch(Object(Dingo\\Api\\Http\\Request))",
            "#28 /var/www/html/extensions/igniter/api/vendor/dingo/api/src/Routing/Router.php(518): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')",
            "#29 /var/www/html/extensions/igniter/api/vendor/dingo/api/src/Http/Middleware/Request.php(126): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
            "#30 /var/www/html/extensions/igniter/api/vendor/illuminate/pipeline/Pipeline.php(128): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#31 /var/www/html/vendor/tastyigniter/flame/src/Setting/Middleware/SaveSetting.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#32 /var/www/html/extensions/igniter/api/vendor/illuminate/pipeline/Pipeline.php(167): Igniter\\Flame\\Setting\\Middleware\\SaveSetting->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#35 /var/www/html/extensions/igniter/api/vendor/illuminate/pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#37 /var/www/html/extensions/igniter/api/vendor/illuminate/pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#39 /var/www/html/extensions/igniter/api/vendor/illuminate/pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#40 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#41 /var/www/html/extensions/igniter/api/vendor/illuminate/pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#42 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#43 /var/www/html/extensions/igniter/api/vendor/illuminate/pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#44 /var/www/html/extensions/igniter/api/vendor/illuminate/pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#45 /var/www/html/extensions/igniter/api/vendor/dingo/api/src/Http/Middleware/Request.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#46 /var/www/html/extensions/igniter/api/vendor/dingo/api/src/Http/Middleware/Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))",
            "#47 /var/www/html/extensions/igniter/api/vendor/illuminate/pipeline/Pipeline.php(167): Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#48 /var/www/html/extensions/igniter/api/vendor/illuminate/pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))",
            "#51 /var/www/html/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))",
            "#52 {main}"
        ]
    }
}
```

**Comment by ryanmitchell** [comment]
Closing as this has been fixed by recent commits
