### ISSUE TITLE
[Bug]: Post api/customers

### ISSUE THREAD

**Issue by devexsolutions** [tastyigniter/ti-ext-api#82]
### What happened?

**Whenever I try to create a client through the API endpoint, you will get the error that I did not provide the required fields**

`{
  "first_name": "Joe",
  "last_name": "Bloggs",
  "email": "joe@bloggs.com",
  "telephone": "1234512345",
  "newsletter": false,
  "status": true,
  "addresses": [
    {
      "address_1": "1 Some Road",
      "address_2": null,
      "city": "London",
      "state": "",
      "postcode": "W1A 3NN",
      "country_id": 222
    }
  ]
}`

### What did you expect to happen?

`Status: 201 Created
{
  "data": [
    {
      "type": "customers",
      "id": "1",
      "attributes": {
        "first_name": "Joe",
        "last_name": "Bloggs",
        "email": "joe@bloggs.com",
        "telephone": "1234512345",
        "newsletter": false,
        "customer_group_id": 1,
        "date_added": "2020-05-20 08:34:37",
        "status": true,
        "full_name": "Joe Bloggs",
        "addresses": [
          {
            "address_id": 1,
            "customer_id": 1,
            "address_1": "1 Some Road",
            "address_2": null,
            "city": "London",
            "state": "",
            "postcode": "W1A 3NN",
            "country_id": 222
          }
        ]
      }
    }
  ]
}`

### Version

3.5.x

### What browser are you seeing the problem on?

Firefox, Chrome, Safari

### Relevant log output

```shell
`{
    "message": "Failed to validate request parameters",
    "errors": {
        "first_name": [
            "The First Name field is required."
        ],
        "last_name": [
            "The Last Name field is required."
        ],
        "email": [
            "The Email field is required."
        ],
        "customer_group_id": [
            "The Customer Group field is required."
        ],
        "status": [
            "The Status field is required."
        ]
    },
    "status_code": 422,
    "debug": {
        "line": 197,
        "file": "/Applications/MAMP/htdocs/tasty/extensions/igniter/api/actions/RestController.php",
        "class": "Dingo\\Api\\Exception\\ResourceException",
        "trace": [
            "#0 /Applications/MAMP/htdocs/tasty/extensions/igniter/api/actions/RestController.php(84): Igniter\\Api\\Actions\\RestController->validateRequest('all')",
            "#1 /Applications/MAMP/htdocs/tasty/extensions/igniter/api/apiresources/Customers.php(45): Igniter\\Api\\Actions\\RestController->store()",
            "#2 [internal function]: Igniter\\Api\\ApiResources\\Customers->store()",
            "#3 /Applications/MAMP/htdocs/tasty/extensions/igniter/api/classes/ApiController.php(43): call_user_func_array(Array, Array)",
            "#4 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Igniter\\Api\\Classes\\ApiController->callAction('store', Array)",
            "#5 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Igniter\\Api\\ApiResources\\Customers), 'store')",
            "#6 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()",
            "#7 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()",
            "#8 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#9 /Applications/MAMP/htdocs/tasty/extensions/igniter/api/vendor/dingo/api/src/Http/Middleware/Auth.php(55): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#10 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dingo\\Api\\Http\\Middleware\\Auth->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#11 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#12 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#13 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(127): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#14 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(103): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest(Object(Dingo\\Api\\Http\\Request), Object(Closure), Array)",
            "#15 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(55): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter(Object(Dingo\\Api\\Http\\Request), Object(Closure), 'api', Object(Closure))",
            "#16 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure), 'api')",
            "#17 /Applications/MAMP/htdocs/tasty/extensions/igniter/api/vendor/dingo/api/src/Http/Middleware/PrepareController.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#18 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dingo\\Api\\Http\\Middleware\\PrepareController->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#19 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#20 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#21 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Dingo\\Api\\Http\\Request))",
            "#22 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute(Object(Dingo\\Api\\Http\\Request), Object(Illuminate\\Routing\\Route))",
            "#23 /Applications/MAMP/htdocs/tasty/vendor/tastyigniter/flame/src/Router/CoreRouter.php(22): Illuminate\\Routing\\Router->dispatchToRoute(Object(Dingo\\Api\\Http\\Request))",
            "#24 /Applications/MAMP/htdocs/tasty/extensions/igniter/api/vendor/dingo/api/src/Routing/Adapter/Laravel.php(88): Igniter\\Flame\\Router\\CoreRouter->dispatch(Object(Dingo\\Api\\Http\\Request))",
            "#25 /Applications/MAMP/htdocs/tasty/extensions/igniter/api/vendor/dingo/api/src/Routing/Router.php(518): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')",
            "#26 /Applications/MAMP/htdocs/tasty/extensions/igniter/api/vendor/dingo/api/src/Http/Middleware/Request.php(126): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
            "#27 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#28 /Applications/MAMP/htdocs/tasty/vendor/tastyigniter/flame/src/Setting/Middleware/SaveSetting.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#29 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Igniter\\Flame\\Setting\\Middleware\\SaveSetting->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#30 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#31 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#32 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#33 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#34 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#35 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#36 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#37 /Applications/MAMP/htdocs/tasty/vendor/fruitcake/laravel-cors/src/HandleCors.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#38 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#39 /Applications/MAMP/htdocs/tasty/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#40 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#41 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#42 /Applications/MAMP/htdocs/tasty/extensions/igniter/api/vendor/dingo/api/src/Http/Middleware/Request.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#43 /Applications/MAMP/htdocs/tasty/extensions/igniter/api/vendor/dingo/api/src/Http/Middleware/Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))",
            "#44 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#45 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#46 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#47 /Applications/MAMP/htdocs/tasty/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))",
            "#48 /Applications/MAMP/htdocs/tasty/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))",
            "#49 {main}"
        ]
    }
}`
```

**Comment by sampoyigi** [comment]
Not reproducible in the latest release. Please reopen this issue if it still occurs, with a set of reproducible steps.
